### ISSUE TITLE
Revisions

### ISSUE THREAD

**Issue by marcjwilliams1** [marcjwilliams1/dnds-clonesize#3]
- [x] Clone size as a function of age #1 
- [x] Site level selection coefficients #2
- [x] Different dN/dS tool (ssb-dn/ds) #4
- [x] Remove cancer sections #7 
- [x] Check inferred delta is not effects by binsize #5 
- [x] Chech influence of passenger mutations #6
